export interface Model {
  id: string;
  slug: string;
  name: string;
  tagline: string;
  nationality: string;
  ethnicity: string;
  gender: string;
  age: number;
  height: string;
  weight: string;
  bio: string;
  hobbies: string;
  specialties: string[];
  thumbnail_url: string;
  main_photos: string[]; // New: Main photos for the modal
  editorial_photos?: string[]; // New: Optional editorial photos
  commercial_photos?: string[]; // New: Optional commercial photos
  runway_photos?: string[]; // New: Optional runway photos
  is_new: boolean;
  is_popular: boolean;
  is_coming_soon: boolean;
  price_usd: number;
}

export const apiService = {
  async getModels() {
    console.log("Loading simple test models...");
    return [
      {
        id: "av01",
        slug: "aria-valen",
        name: "Aria Valen",
        tagline: "Luxury Runway Specialist",
        nationality: "Italian",
        ethnicity: "Caucasian",
        gender: "Female",
        age: 27,
        height: "178cm",
        weight: "56kg",
        bio: "Professional luxury runway and high-fashion model with expertise in swimwear and resort wear campaigns.",
        hobbies: "Sailing, oil painting, Classical music",
        specialties: ["Luxury runway", "high-fashion", "swimwear"],
        thumbnail_url: "https://storage.googleapis.com/cyberchicmodels-media/models/thumbnails/av01-aria-valen-thumbnail.webp",
        main_photos: [
          "https://storage.googleapis.com/cyberchicmodels-media/models/aria-valen/av01-aria-valen-main-1.webp",
          "https://storage.googleapis.com/cyberchicmodels-media/models/aria-valen/av01-aria-valen-main-2.webp",
        ],
        editorial_photos: [
          "https://storage.googleapis.com/cyberchicmodels-media/models/aria-valen/av01-aria-valen-editorial-1.webp",
          "https://storage.googleapis.com/cyberchicmodels-media/models/aria-valen/av01-aria-valen-editorial-2.webp",
        ],
        commercial_photos: [
          "https://storage.googleapis.com/cyberchicmodels-media/models/aria-valen/av01-aria-valen-commercial-1.webp",
        ],
        is_new: false,
        is_popular: true,
        is_coming_soon: false,
        price_usd: 99.0,
      },
      {
        id: "nv01",
        slug: "nova-vion",
        name: "Nova Vion",
        tagline: "Beauty & Product Specialist",
        nationality: "American",
        ethnicity: "Caucasian",
        gender: "Female",
        age: 24,
        height: "176cm",
        weight: "58kg",
        bio: "Specialized beauty and premium product model with a keen eye for fashion concepts.",
        hobbies: "Sketching fashion concepts, travel photography",
        specialties: ["Beauty close-ups", "product modeling"],
        thumbnail_url: "https://storage.googleapis.com/cyberchicmodels-media/models/thumbnails/nv01-nova-vion-thumbnail.webp",
        main_photos: [
          "https://storage.googleapis.com/cyberchicmodels-media/models/nova-vion/nv01-nova-vion-main-1.webp",
          "https://storage.googleapis.com/cyberchicmodels-media/models/nova-vion/nv01-nova-vion-main-2.webp",
        ],
        editorial_photos: [
          "https://storage.googleapis.com/cyberchicmodels-media/models/nova-vion/nv01-nova-vion-editorial-1.webp",
        ],
        is_new: false,
        is_popular: false,
        is_coming_soon: false,
        price_usd: 99.0,
      },
      {
        id: "fm01",
        slug: "freja-madsen",
        name: "Freja Madsen",
        tagline: "Contemporary Lifestyle",
        nationality: "Finnish",
        ethnicity: "Caucasian",
        gender: "Female",
        age: 20,
        height: "180cm",
        weight: "56kg",
        bio: "Young contemporary lifestyle model specializing in morning editorials and wellness campaigns.",
        hobbies: "Light yoga and stretching, morning journaling",
        specialties: ["Contemporary lifestyle", "morning editorials"],
        thumbnail_url: "https://storage.googleapis.com/cyberchicmodels-media/models/thumbnails/fm01-freja-madsen-thumbnail.webp",
        main_photos: [
          "https://storage.googleapis.com/cyberchicmodels-media/models/freja-madsen/fm01-freja-madsen-main-1.webp",
        ],
        is_new: true,
        is_popular: false,
        is_coming_soon: false,
        price_usd: 99.0,
      },
      {
        id: "nea01",
        slug: "noura-el-amine",
        name: "Noura El Amine",
        tagline: "Editorial & High Fashion",
        nationality: "Egyptian",
        ethnicity: "Arab",
        gender: "Female",
        age: 25,
        height: "175cm",
        weight: "52kg",
        bio: "Editorial and high fashion model with expertise in luxury jewelry and accessories campaigns.",
        hobbies: "Architecture, interior design, cultural photography",
        specialties: ["Editorial", "high fashion", "luxury jewelry"],
        thumbnail_url: "https://storage.googleapis.com/cyberchicmodels-media/models/thumbnails/nea01-noura-el-amine-thumbnail.webp",
        main_photos: [
          "https://storage.googleapis.com/cyberchicmodels-media/models/noura-el-amine/nea01-noura-el-amine-main-1.webp",
        ],
        is_new: false,
        is_popular: false,
        is_coming_soon: false,
        price_usd: 99.0,
      },
      {
        id: "zs01",
        slug: "zeina-s",
        name: "Zeina S",
        tagline: "Luxury Lifestyle & Jewelry",
        nationality: "Lebanese",
        ethnicity: "Arab",
        gender: "Female",
        age: 28,
        height: "170cm",
        weight: "50kg",
        bio: "Luxury lifestyle and jewelry specialist model with expertise in high-end accessories.",
        hobbies: "Jewelry design, luxury travel, fine dining",
        specialties: ["Luxury lifestyle", "jewelry campaigns"],
        thumbnail_url: "https://storage.googleapis.com/cyberchicmodels-media/models/thumbnails/zs01-zeina-s-thumbnail.webp",
        main_photos: [
          "https://storage.googleapis.com/cyberchicmodels-media/models/zeina-s/zs01-zeina-s-main-1.webp",
        ],
        is_new: false,
        is_popular: false,
        is_coming_soon: false,
        price_usd: 99.0,
      },
      {
        id: "ln01",
        slug: "layal-n",
        name: "Layal N",
        tagline: "Refined Elegance",
        nationality: "Lebanese",
        ethnicity: "Arab",
        gender: "Female",
        age: 24,
        height: "168cm",
        weight: "49kg",
        bio: "Editorial fashion model specializing in refined elegance and luxury campaigns.",
        hobbies: "Art history, classical music, cultural events",
        specialties: ["Editorial fashion", "luxury campaigns"],
        thumbnail_url: "https://storage.googleapis.com/cyberchicmodels-media/models/thumbnails/ln01-layal-n-thumbnail.webp",
        main_photos: [
          "https://storage.googleapis.com/cyberchicmodels-media/models/layal-n/ln01-layal-n-main-1.webp",
        ],
        is_new: false,
        is_popular: false,
        is_coming_soon: false,
        price_usd: 99.0,
      },
      {
        id: "mi01",
        slug: "mariia-ivanova",
        name: "Mariia Ivanova",
        tagline: "Runway & Catwalk",
        nationality: "Ukrainian",
        ethnicity: "Caucasian",
        gender: "Female",
        age: 27,
        height: "181cm",
        weight: "57kg",
        bio: "Professional runway and catwalk model with international fashion week experience.",
        hobbies: "Ballet, contemporary dance, fashion design",
        specialties: ["Runway", "catwalk", "fashion shows"],
        thumbnail_url: "https://storage.googleapis.com/cyberchicmodels-media/models/thumbnails/mi01-mariia-ivanova-thumbnail.webp",
        main_photos: [
          "https://storage.googleapis.com/cyberchicmodels-media/models/mariia-ivanova/mi01-mariia-ivanova-main-1.webp",
        ],
        is_new: false,
        is_popular: false,
        is_coming_soon: true,
        price_usd: 99.0,
      },
      {
        id: "zw01",
        slug: "zofia-wrobel",
        name: "Zofia Wrobel",
        tagline: "Editorial & Minimalist",
        nationality: "Polish",
        ethnicity: "Caucasian",
        gender: "Female",
        age: 40,
        height: "160cm",
        weight: "48kg",
        bio: "Mature editorial model specializing in chic, minimalist aesthetics and natural beauty campaigns.",
        hobbies: "Skiing, dancing, photography",
        specialties: ["Editorial", "minimalist", "natural beauty"],
        thumbnail_url: "https://storage.googleapis.com/cyberchicmodels-media/models/thumbnails/zw01-zofia-wrobel-thumbnail.webp",
        main_photos: [
          "https://storage.googleapis.com/cyberchicmodels-media/models/zofia-wrobel/zw01-zofia-wrobel-main-1.webp",
        ],
        is_new: false,
        is_popular: false,
        is_coming_soon: false,
        price_usd: 99.0,
      },
      {
        id: "vr01",
        slug: "vanessa-rivera",
        name: "Vanessa Rivera",
        tagline: "Luxury Lifestyle & Glamour",
        nationality: "Italian",
        ethnicity: "Caucasian",
        gender: "Female",
        age: 23,
        height: "174cm",
        weight: "53kg",
        bio: "Luxury lifestyle and glamour model with expertise in high-end fashion and beauty campaigns.",
        hobbies: "Fashion styling, luxury travel, wine tasting",
        specialties: ["Luxury lifestyle", "glamour", "high-end fashion"],
        thumbnail_url: "https://storage.googleapis.com/cyberchicmodels-media/models/thumbnails/vr01-vanessa-rivera-thumbnail.webp",
        main_photos: [
          "https://storage.googleapis.com/cyberchicmodels-media/models/vanessa-rivera/vr01-vanessa-rivera-main-1.webp",
        ],
        is_new: true,
        is_popular: false,
        is_coming_soon: false,
        price_usd: 99.0,
      },
      {
        id: "ev01",
        slug: "elara-vey",
        name: "Elara Vey",
        tagline: "Fashion & Catwalk",
        nationality: "French",
        ethnicity: "Caucasian",
        gender: "Female",
        age: 25,
        height: "179cm",
        weight: "55kg",
        bio: "Fashion and catwalk model with Parisian elegance and international runway experience.",
        hobbies: "Contemporary art, fashion photography, cultural events",
        specialties: ["Fashion", "catwalk", "contemporary style"],
        thumbnail_url: "https://storage.googleapis.com/cyberchicmodels-media/models/thumbnails/ev01-elara-vey-thumbnail.webp",
        main_photos: [
          "https://storage.googleapis.com/cyberchicmodels-media/models/elara-vey/ev01-elara-vey-main-1.webp",
        ],
        is_new: false,
        is_popular: true,
        is_coming_soon: false,
        price_usd: 99.0,
      },
      {
        id: "ch01",
        slug: "camila-huaman",
        name: "Camila Huaman",
        tagline: "Editorial & E-commerce",
        nationality: "Peruvian",
        ethnicity: "Latino",
        gender: "Female",
        age: 29,
        height: "172cm",
        weight: "54kg",
        bio: "Versatile editorial and e-commerce model with strong beauty campaign experience.",
        hobbies: "Travel, singing, fashion",
        specialties: ["Editorial", "e-commerce", "beauty campaigns"],
        thumbnail_url: "https://storage.googleapis.com/cyberchicmodels-media/models/thumbnails/ch01-camila-huaman-thumbnail.webp",
        main_photos: [
          "https://storage.googleapis.com/cyberchicmodels-media/models/camila-huaman/ch01-camila-huaman-main-1.webp",
        ],
        is_new: false,
        is_popular: false,
        is_coming_soon: false,
        price_usd: 99.0,
      },
    ];
  },
};

